---
  - name: Ensure Group devops exists
    group:
      name: devops
      state: present

  - name: User Creation - devops
    user:
      name: devops
      group: devops
      state: present
      password: '$1$K27AogF.$2W/MTTta2ZLJrNP73RmgV0'

  - name: Add Extras Repositories
    shell: yum-config-manager --enable extras

  - name: Install Mandatory Packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
       - amazon-linux-extras
       - git
       - java-11-amazon-corretto
       - logrotate
       - python3
       - python3-pip

  - name: Git Kafdrop Stable Version Checkout
    ansible.builtin.git:
      repo: "{{ kafdrop_repo_location }}"
      dest: "{{ kafdrop_location }}"
      version: "{{ kafdrop_stable_version }}"
      force: yes

  - name: Copy cacerts File
    ansible.builtin.copy:
      src: /usr/lib/jvm/java-11-amazon-corretto.x86_64/lib/security/cacerts
      dest: "{{ kafdrop_location }}/{{ truststore_name }}"
      remote_src: yes
      owner: devops
      group: devops
      mode: '0644'

  - name: Generate Private Key
    shell: "keytool -genkey -keystore {{ kafdrop_location }}/{{ keystore_name }} -validity {{ key_validity }} -storepass changeit -keypass changeit -dname \"CN={{ msk_alias }}\" -alias {{ msk_alias }} -storetype pkcs12"
    ignore_errors: yes

  - name: Generate Certificate Request
    shell: "keytool -keystore {{ kafdrop_location }}/{{ keystore_name }} -certreq -file {{ kafdrop_location }}/client-cert-sign-request -alias {{ msk_alias }} -storepass changeit -keypass changeit"
    ignore_errors: yes

  - name: Replace Content in client-cert-sign-request start of the file
    ansible.builtin.replace:
      path: "{{ kafdrop_location }}/client-cert-sign-request"
      regexp: 'BEGIN NEW CERTIFICATE REQUEST'
      replace: 'BEGIN CERTIFICATE REQUEST'

  - name: Replace Content in client-cert-sign-request end of the file
    ansible.builtin.replace:
      path: "{{ kafdrop_location }}/client-cert-sign-request"
      regexp: 'END NEW CERTIFICATE REQUEST'
      replace: 'END CERTIFICATE REQUEST'

  - name: Creates Kafdrop Properties File
    copy:
      src: kafka.properties
      dest: "{{ kafdrop_location }}"
      owner: devops
      group: devops
      mode: '0644'

  - name: Build Kafdrop
    command: bash -lc "cd {{ kafdrop_location }}/ && ./mvnw package"

  - name: Change Folder Content Ownership
    ansible.builtin.file:
      path: "{{ kafdrop_location }}"
      state: directory
      recurse: yes
      owner: devops
      group: devops
      mode: 0755

  - name: Creates Kafdrop Destination Folder
    file:
      path: "{{ kafdrop_executable_location }}"
      state: directory
      owner: devops
      group: devops
      mode: 0755

  - name: Creates Kafdrop Logs Destination Folder
    file:
      path: "{{ kafdrop_logs_location }}"
      state: directory
      owner: devops
      group: devops
      mode: 0755

  - name: Initialize kafdrop-collector Log File
    file:
      path: "{{ kafdrop_logs_location }}kafdrop-collector.log"
      state: touch
      owner: devops
      group: devops
      mode: 0755

  - name: Copy Kafdrop Binaries File
    copy:
      src: "{{ kafdrop_location }}/target/kafdrop-{{ kafdrop_stable_version }}.jar"
      dest: "{{ kafdrop_executable_location }}/kafdrop.jar"
      owner: devops
      group: devops
      remote_src: yes
      mode: 0755

  - name: Copy Kafdrop Properties File
    copy:
      src: "{{ kafdrop_location }}/kafka.properties"
      dest: "{{ kafdrop_executable_location }}"
      mode: 0755
      owner: devops
      group: devops
      remote_src: yes

  - name: Copy kafdrop Service File
    copy:
      src: kafdrop.service
      dest: /etc/systemd/system
      mode: 0755

  - name: Copy kafdrop run.sh file
    copy:
      src: kafdrop-run.sh
      dest: "{{ kafdrop_executable_location }}"
      mode: 0755
      owner: devops
      group: devops

  - name: Copy Kafdrop Collector Script
    copy:
      src: kafdrop-collector.py
      dest: "{{ kafdrop_executable_location }}"
      mode: 0755
      owner: devops
      group: devops

  - name: Copy Kafdrop Log Rotate Configuration File
    copy:
      src: kafdrop-log.conf
      dest: /etc/logrotate.d/
      mode: 0755
      owner: devops
      group: devops

  - name: Start Kafdrop Service
    systemd:
      name: kafdrop
      state: started
      enabled: yes
    ignore_errors: yes
    become: true

  - name: Install requests Module for Python3
    pip:
      name: requests
      executable: pip3

  - name: Set Kafdrop Collector Crontab Job
    ansible.builtin.cron:
      name: "Collect Kafdrop Metrics"
      minute: "*"
      job: "python3 {{ kafdrop_executable_location }}kafdrop-collector.py {{ kafdrop_address }} &> {{ kafdrop_logs_location }}kafdrop-collector.log"
    become: true
